# Generated by Django 4.2.7 on 2023-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioextraction',
            name='video',
            field=models.FileField(default=None, null=True, upload_to='audio_extraction/'),
        ),
    ]
