# Generated by Django 4.2.7 on 2023-11-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_extraction', '0002_audioextraction_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioextraction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='audioextraction',
            name='timestamp',
        ),
    ]
