# Generated by Django 4.2.7 on 2023-11-11 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audio_extraction', '0003_remove_audioextraction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioextraction',
            name='extraction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
