# Generated by Django 4.2.7 on 2023-11-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_extraction', '0005_audioextraction_audio_alter_audioextraction_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioextraction',
            old_name='extraction_date',
            new_name='extraction_timestamp',
        ),
    ]
